Update patches
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

diff --git a/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch b/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch
--- a/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch
+++ b/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch
@@ -1,25 +1,27 @@
-From 6b216b68dca516fbf9b2f11b89134c8b7f37e6b3 Mon Sep 17 00:00:00 2001
+From a2f44fd4822d941435b0dd4bab50d3ea2c3aae3a Mon Sep 17 00:00:00 2001
 From: Piotr Gorski <lucjan.lucjanov@gmail.com>
-Date: Mon, 31 Oct 2022 20:07:16 +0100
+Date: Wed, 2 Nov 2022 09:36:40 +0100
 Subject: [PATCH] mkinitcpio cachyos
 
 Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>
 ---
- Makefile                                 |  3 +-
- functions                                | 67 ++++++++++++-----
- install/strip                            |  1 +
- libalpm/hooks/60-mkinitcpio-remove.hook  |  2 +-
- libalpm/hooks/90-mkinitcpio-install.hook |  2 +-
- libalpm/scripts/mkinitcpio               | 95 ++++++++++++++++++++++++
- libalpm/scripts/mkinitcpio-install       | 44 -----------
- libalpm/scripts/mkinitcpio-remove        | 61 ---------------
- man/mkinitcpio.8.txt                     |  6 ++
- man/mkinitcpio.conf.5.txt                |  8 +-
- mkinitcpio                               | 52 +++++++++++--
- mkinitcpio.conf                          |  6 ++
- shell/bash-completion                    |  2 +-
- shell/zsh-completion                     |  1 +
- 14 files changed, 212 insertions(+), 138 deletions(-)
+ Makefile                                 |   3 +-
+ functions                                | 143 ++++++++++++++++++-----
+ install/fsck                             |  37 +++---
+ install/strip                            |   1 +
+ libalpm/hooks/60-mkinitcpio-remove.hook  |   2 +-
+ libalpm/hooks/90-mkinitcpio-install.hook |   2 +-
+ libalpm/scripts/mkinitcpio               |  95 +++++++++++++++
+ libalpm/scripts/mkinitcpio-install       |  44 -------
+ libalpm/scripts/mkinitcpio-remove        |  61 ----------
+ lsinitcpio                               |  48 +-------
+ man/mkinitcpio.8.txt                     |   6 +
+ man/mkinitcpio.conf.5.txt                |   8 +-
+ mkinitcpio                               |  52 +++++++--
+ mkinitcpio.conf                          |  28 +++--
+ shell/bash-completion                    |   2 +-
+ shell/zsh-completion                     |   1 +
+ 16 files changed, 315 insertions(+), 218 deletions(-)
  create mode 100644 libalpm/scripts/mkinitcpio
  delete mode 100644 libalpm/scripts/mkinitcpio-install
  delete mode 100644 libalpm/scripts/mkinitcpio-remove
@@ -40,10 +42,96 @@ index 9ef0f6a..e6f3789 100644
  doc: $(MANPAGES)
  man/%: man/%.txt Makefile
 diff --git a/functions b/functions
-index 2148ed8..120874c 100644
+index 2148ed8..7e58cc3 100644
 --- a/functions
 +++ b/functions
-@@ -574,7 +574,15 @@ add_file() {
+@@ -147,18 +147,79 @@ kver_x86() {
+     printf '%s' "$kver"
+ }
+ 
++detect_compression() {
++    local bytes
++
++    read -rd '' bytes < <(hexdump -n 6 -e '"%c"' "$1")
++    case $bytes in
++        $'\xfd7zXZ')
++            echo 'xz'
++            return
++            ;;
++    esac
++
++    read -rd '' bytes < <(hexdump -n 4 -e '"%c"' "$1")
++    if [[ $bytes = $'\x89LZO' ]]; then
++        echo 'lzop'
++        return
++    fi
++
++    read -rd '' bytes < <(hexdump -n 2 -e '"%x"' "$1")
++    if [[ $bytes = '8b1f' ]]; then
++        echo 'gzip'
++        return
++    fi
++
++    read -rd '' bytes < <(hexdump -n 4 -e '"%x"' "$1")
++    case $bytes in
++        184d2204)
++            error 'Newer lz4 stream format detected! This may not boot!'
++            echo 'lz4'
++            return
++            ;;
++        184c2102)
++            echo 'lz4 -l'
++            return
++            ;;
++        fd2fb528)
++            echo 'zstd'
++            return
++            ;;
++    esac
++
++    read -rd '' bytes < <(hexdump -n 3 -e '"%c"' "$1")
++    if [[ $bytes == 'BZh' ]]; then
++        echo 'bzip2'
++        return
++    fi
++
++    # lzma detection sucks and there's really no good way to
++    # do it without reading large portions of the stream. this
++    # check is good enough for GNU tar, apparently, so it's good
++    # enough for me.
++    read -rd '' bytes < <(hexdump -n 3 -e '"%x"' "$1")
++    if [[ $bytes = '5d' ]]; then
++        echo 'lzma'
++        return
++    fi
++
++    # out of ideas, assuming uncompressed
++}
++
+ kver_generic() {
+-    # For unknown architectures, we can try to grep the uncompressed
++    # For unknown architectures, we can try to grep the uncompressed or gzipped
+     # image for the boot banner.
+-    # This should work at least for ARM when run on /boot/Image. On
+-    # other architectures it may be worth trying rather than bailing,
+-    # and inform the user if none was found.
++    # This should work at least for ARM when run on /boot/Image, or RISC-V on
++    # gzipped /boot/vmlinuz-linuz. On other architectures it may be worth trying
++    # rather than bailing, and inform the user if none was found.
+ 
+     # Loosely grep for `linux_banner`:
+     # https://elixir.bootlin.com/linux/v5.7.2/source/init/version.c#L46
+-    local kver=
++    local kver= reader=cat
++    
++    [[ $(detect_compression "$1") == 'gzip' ]] && reader=zcat
+ 
+-    read _ _ kver _ < <(grep -m1 -aoE 'Linux version .(\.[-[:alnum:]+]+)+' "$1")
++    read _ _ kver _ < <($reader "$1" | grep -m1 -aoE 'Linux version .(\.[-[:alnum:]+]+)+')
+ 
+     printf '%s' "$kver"
+ }
+@@ -574,7 +635,15 @@ add_file() {
      else
          quiet "adding file: %s" "$dest"
      fi
@@ -60,7 +148,7 @@ index 2148ed8..120874c 100644
  }
  
  add_runscript() {
-@@ -634,7 +642,15 @@ add_binary() {
+@@ -634,7 +703,15 @@ add_binary() {
      mode=$(stat -c %a "$binary")
  
      # always add the binary itself
@@ -77,7 +165,16 @@ index 2148ed8..120874c 100644
  
      # negate this so that the RETURN trap is not fired on non-binaries
      ! lddout=$(ldd "$binary" 2>/dev/null) && return 0
-@@ -777,8 +793,19 @@ initialize_buildroot() {
+@@ -736,7 +813,7 @@ initialize_buildroot() {
+     # creates a temporary directory for the buildroot and initialize it with a
+     # basic set of necessary directories and symlinks
+ 
+-    local workdir= kernver=$1 arch=$(uname -m) buildroot
++    local workdir= kernver=$1 arch=$(uname -m) buildroot osreleasefile
+ 
+     if ! workdir=$(mktemp -d --tmpdir mkinitcpio.XXXXXX); then
+         error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
+@@ -777,8 +854,20 @@ initialize_buildroot() {
      ln -s /proc/self/mounts "$buildroot/etc/mtab"
      >"$buildroot/etc/fstab"
  
@@ -86,12 +183,13 @@ index 2148ed8..120874c 100644
 +    # add os-release and initrd-release for systemd
 +    if [[ -e /etc/os-release ]]; then
 +        if [[ -L /etc/os-release ]]; then
-+            install -Dm0644 /etc/os-release "${buildroot}$(realpath -- /etc/os-release)"
-+            ln -sT  "$(realpath -- /etc/os-release)" "$buildroot/etc/os-release"
-+            ln -sT "$(realpath -- /etc/os-release)" "$buildroot/etc/initrd-release"
++            osreleasefile="$(realpath -- /etc/os-release)"
++            install -Dm0644 "$osreleasefile" "${buildroot}${osreleasefile}"
++            cp -adT /etc/os-release "${buildroot}/etc/os-release"
++            cp -adT /etc/os-release "${buildroot}/etc/initrd-release"
 +        else
-+            install -Dm0644 /etc/os-release "$buildroot/etc/os-release"
-+            ln -sT os-release "$buildroot/etc/initrd-release"
++            install -Dm0644 /etc/os-release "${buildroot}/etc/os-release"
++            ln -sT os-release "${buildroot}/etc/initrd-release"
 +        fi
 +    else
 +        >"$buildroot/etc/initrd-release"
@@ -99,7 +197,7 @@ index 2148ed8..120874c 100644
  
      # add a blank ld.so.conf to keep ldconfig happy
      >"$buildroot/etc/ld.so.conf"
-@@ -849,7 +876,7 @@ try_enable_color() {
+@@ -849,7 +938,7 @@ try_enable_color() {
  
  install_modules() {
      local m moduledest=$BUILDROOT/lib/modules/$KERNELVERSION
@@ -108,7 +206,7 @@ index 2148ed8..120874c 100644
  
      [[ $KERNELVERSION == none ]] && return 0
  
-@@ -860,20 +887,22 @@ install_modules() {
+@@ -860,20 +949,22 @@ install_modules() {
  
      cp "$@" "$moduledest/kernel"
  
@@ -145,6 +243,70 @@ index 2148ed8..120874c 100644
      (( ${#xz_comp[*]} )) && xz -d "${xz_comp[@]}"
      (( ${#gz_comp[*]} )) && gzip -d "${gz_comp[@]}"
      (( ${#zst_comp[*]} )) && zstd -d --rm -q "${zst_comp[@]}"
+diff --git a/install/fsck b/install/fsck
+index 4f5cf93..e394e0d 100644
+--- a/install/fsck
++++ b/install/fsck
+@@ -4,18 +4,26 @@ build() {
+     local fsck= added=0
+ 
+     add_fsck() {
+-        [[ $1 = tmpfs ]] && return
+-
+-        if [[ $1 = ext[234] ]]; then
+-            add_binary fsck.ext4
+-            add_symlink /usr/bin/fsck.ext2 fsck.ext4
+-            add_symlink /usr/bin/fsck.ext3 fsck.ext4
+-        elif [[ $1 = xfs ]]; then
++        case "$1" in
++        ext[234])
++            add_binary e2fsck
++            add_symlink /usr/bin/fsck.ext2 e2fsck
++            add_symlink /usr/bin/fsck.ext3 e2fsck
++            add_symlink /usr/bin/fsck.ext4 e2fsck
++            [[ -e /etc/e2fsck.conf ]] && add_file /etc/e2fsck.conf
++            ;;
++        xfs)
+             add_binary fsck.xfs
+             add_binary xfs_repair
+-        else
+-            add_binary "fsck.$1"
+-        fi
++            ;;
++        *)
++            if compgen -c "fsck.$1" &> /dev/null; then
++                add_binary "fsck.$1"
++            else
++                return 1
++            fi
++            ;;
++        esac
+     }
+ 
+     if (( ! fs_autodetect_failed )) && [[ $rootfstype$usrfstype ]]; then
+@@ -26,9 +34,8 @@ build() {
+             add_fsck $usrfstype && (( ++added ))
+         fi
+     else
+-        for fsck in /usr/bin/fsck.* /usr/bin/xfs_repair; do
+-            [[ -f $fsck ]] || continue
+-            add_binary "$fsck" && (( ++added ))
++        for fsck in $(compgen -c fsck.); do
++            add_fsck "${fsck#fsck.}" && (( ++added ))
+         done
+     fi
+ 
+@@ -38,10 +45,6 @@ build() {
+     fi
+ 
+     add_binary fsck
+-    if [[ -e /etc/e2fsck.conf ]]; then
+-        add_file /etc/e2fsck.conf
+-    fi
+-
+ }
+ 
+ help() {
 diff --git a/install/strip b/install/strip
 index f8eb49d..b71ed54 100644
 --- a/install/strip
@@ -181,7 +343,7 @@ index cf480bd..5b02fb8 100644
  NeedsTargets
 diff --git a/libalpm/scripts/mkinitcpio b/libalpm/scripts/mkinitcpio
 new file mode 100644
-index 0000000..4ef56e2
+index 0000000..0a75ee1
 --- /dev/null
 +++ b/libalpm/scripts/mkinitcpio
 @@ -0,0 +1,95 @@
@@ -220,10 +382,10 @@ index 0000000..4ef56e2
 +    fi
 +
 +    # always install the kernel
-+    install -Dm644 "${line}" "/boot/vmlinuz-${1}"
++    install -Dm644 "$line" "/boot/vmlinuz-${1}"
 +
 +    # compound args for each kernel
-+    args+=(-p "${1}")
++    args+=(-p "$1")
 +}
 +
 +remove_kernel() {
@@ -235,7 +397,7 @@ index 0000000..4ef56e2
 +    # remove the installed kernel
 +    rm -f -- "$kernel"
 +
-+    process_preset "${1}" "$preset"
++    process_preset "$1" "$preset"
 +
 +    # remove images
 +    rm -f -- "$initramfs" "$fallback_initramfs"
@@ -397,6 +559,68 @@ index 17b4b31..0000000
 -    done
 -    shopt -u nullglob
 -fi
+diff --git a/lsinitcpio b/lsinitcpio
+index 4715783..f5c43ef 100755
+--- a/lsinitcpio
++++ b/lsinitcpio
+@@ -84,54 +84,12 @@ detect_filetype() {
+             echo
+             return
+             ;;
+-        $'\xfd7zXZ')
+-            echo 'xz'
+-            return
+-            ;;
+     esac
+ 
+-    read -rd '' bytes < <(hexdump -n 4 -e '"%c"' "$1")
+-    if [[ $bytes = $'\x89LZO' ]]; then
+-        echo 'lzop'
+-        return
+-    fi
+-
+-    read -rd '' bytes < <(hexdump -n 2 -e '"%x"' "$1")
+-    if [[ $bytes = '8b1f' ]]; then
+-        echo 'gzip'
+-        return
+-    fi
+-
+-    read -rd '' bytes < <(hexdump -n 4 -e '"%x"' "$1")
+-    case $bytes in
+-        184d2204)
+-            error 'Newer lz4 stream format detected! This may not boot!'
+-            echo 'lz4'
+-            return
+-            ;;
+-        184c2102)
+-            echo 'lz4 -l'
+-            return
+-            ;;
+-        fd2fb528)
+-            echo 'zstd'
+-            return
+-            ;;
+-    esac
+-
+-    read -rd '' bytes < <(hexdump -n 3 -e '"%c"' "$1")
+-    if [[ $bytes == 'BZh' ]]; then
+-        echo 'bzip2'
+-        return
+-    fi
++    compression=$(detect_compression "$1")
+ 
+-    # lzma detection sucks and there's really no good way to
+-    # do it without reading large portions of the stream. this
+-    # check is good enough for GNU tar, apparently, so it's good
+-    # enough for me.
+-    read -rd '' bytes < <(hexdump -n 3 -e '"%x"' "$1")
+-    if [[ $bytes = '5d' ]]; then
+-        echo 'lzma'
++    if [[ -n "$compression" ]]; then
++        echo "$compression"
+         return
+     fi
+ 
 diff --git a/man/mkinitcpio.8.txt b/man/mkinitcpio.8.txt
 index 0360a6b..ced9ec6 100644
 --- a/man/mkinitcpio.8.txt
@@ -572,9 +796,56 @@ index 2781e3a..15e7e57 100755
  BUILDROOT=${_opttargetdir:-$_d_workdir/root}
  
 diff --git a/mkinitcpio.conf b/mkinitcpio.conf
-index 3494fab..8acf414 100644
+index 3494fab..710e05f 100644
 --- a/mkinitcpio.conf
 +++ b/mkinitcpio.conf
+@@ -3,7 +3,7 @@
+ # The following modules are loaded before any boot hooks are
+ # run.  Advanced users may wish to specify all system modules
+ # in this array.  For instance:
+-#     MODULES=(piix ide_disk reiserfs)
++#     MODULES=(usbhid xhci_hcd)
+ MODULES=()
+ 
+ # BINARIES
+@@ -29,27 +29,27 @@ FILES=()
+ # 'filesystems' is _required_ unless you specify your fs modules in MODULES
+ # Examples:
+ ##   This setup specifies all modules in the MODULES setting above.
+-##   No raid, lvm2, or encrypted root is needed.
++##   No RAID, lvm2, or encrypted root is needed.
+ #    HOOKS=(base)
+ #
+ ##   This setup will autodetect all modules for your system and should
+ ##   work as a sane default
+-#    HOOKS=(base udev autodetect block filesystems)
++#    HOOKS=(base udev autodetect modconf block filesystems fsck)
+ #
+ ##   This setup will generate a 'full' image which supports most systems.
+ ##   No autodetection is done.
+-#    HOOKS=(base udev block filesystems)
++#    HOOKS=(base udev modconf block filesystems fsck)
+ #
+-##   This setup assembles a pata mdadm array with an encrypted root FS.
+-##   Note: See 'mkinitcpio -H mdadm' for more information on raid devices.
+-#    HOOKS=(base udev block mdadm encrypt filesystems)
++##   This setup assembles a mdadm array with an encrypted root file system.
++##   Note: See 'mkinitcpio -H mdadm_udev' for more information on RAID devices.
++#    HOOKS=(base udev modconf keyboard keymap consolefont block mdadm_udev encrypt filesystems fsck)
+ #
+-##   This setup loads an lvm2 volume group on a usb device.
+-#    HOOKS=(base udev block lvm2 filesystems)
++##   This setup loads an lvm2 volume group.
++#    HOOKS=(base udev modconf block lvm2 filesystems fsck)
+ #
+ ##   NOTE: If you have /usr on a separate partition, you MUST include the
+-#    usr, fsck and shutdown hooks.
+-HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)
++#    usr and fsck hooks.
++HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block filesystems fsck)
+ 
+ # COMPRESSION
+ # Use this to compress the initramfs image. By default, zstd compression
 @@ -65,3 +65,9 @@ HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)
  # COMPRESSION_OPTIONS
  # Additional options for the compressor
