Update patches
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

diff --git a/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch b/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch
--- a/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch
+++ b/mkinitcpio-cachyos/0001-mkinitcpio-cachyos.patch
@@ -1,6 +1,6 @@
-From 9d9b7eab5d926058a989e666c8dd2f84112bf1c4 Mon Sep 17 00:00:00 2001
+From 6b216b68dca516fbf9b2f11b89134c8b7f37e6b3 Mon Sep 17 00:00:00 2001
 From: Piotr Gorski <lucjan.lucjanov@gmail.com>
-Date: Fri, 28 Oct 2022 15:22:07 +0200
+Date: Mon, 31 Oct 2022 20:07:16 +0100
 Subject: [PATCH] mkinitcpio cachyos
 
 Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>
@@ -13,10 +13,13 @@ Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>
  libalpm/scripts/mkinitcpio               | 95 ++++++++++++++++++++++++
  libalpm/scripts/mkinitcpio-install       | 44 -----------
  libalpm/scripts/mkinitcpio-remove        | 61 ---------------
+ man/mkinitcpio.8.txt                     |  6 ++
  man/mkinitcpio.conf.5.txt                |  8 +-
- mkinitcpio                               |  2 +
+ mkinitcpio                               | 52 +++++++++++--
  mkinitcpio.conf                          |  6 ++
- 11 files changed, 162 insertions(+), 129 deletions(-)
+ shell/bash-completion                    |  2 +-
+ shell/zsh-completion                     |  1 +
+ 14 files changed, 212 insertions(+), 138 deletions(-)
  create mode 100644 libalpm/scripts/mkinitcpio
  delete mode 100644 libalpm/scripts/mkinitcpio-install
  delete mode 100644 libalpm/scripts/mkinitcpio-remove
@@ -394,6 +397,23 @@ index 17b4b31..0000000
 -    done
 -    shopt -u nullglob
 -fi
+diff --git a/man/mkinitcpio.8.txt b/man/mkinitcpio.8.txt
+index 0360a6b..ced9ec6 100644
+--- a/man/mkinitcpio.8.txt
++++ b/man/mkinitcpio.8.txt
+@@ -84,6 +84,12 @@ Options
+ 	/etc/mkinitcpio.d (without the .preset extension) or a full, absolute path to a
+ 	file. This option may be specified multiple times to process multiple presets.
+ 
++*-R, \--remove*::
++	Remove initramfs image(s) generated by the specified preset(s).
++	If used in combination with '-P|--allpresets', removes the images for
++	all presets. This option can only be used with either '-p|--presets' or
++	'-P|--allpresets'.
++
+ *-r, \--moduleroot* 'root'::
+ 	Specifies the root directory to find modules in, defaulting to '/'.
+ 
 diff --git a/man/mkinitcpio.conf.5.txt b/man/mkinitcpio.conf.5.txt
 index 0383360..fdb8d91 100644
 --- a/man/mkinitcpio.conf.5.txt
@@ -418,10 +438,131 @@ index 0383360..fdb8d91 100644
 -Copyright (c) Arch Linux 2006-2021
 +Copyright (c) Arch Linux 2006-2022
 diff --git a/mkinitcpio b/mkinitcpio
-index 2781e3a..687f2b6 100755
+index 2781e3a..15e7e57 100755
 --- a/mkinitcpio
 +++ b/mkinitcpio
-@@ -658,6 +658,8 @@ if [[ $KERNELVERSION != 'none' ]]; then
+@@ -24,7 +24,7 @@ _optmoduleroot= _optgenimg=
+ _optcompress= _opttargetdir=
+ _optosrelease=
+ _optuefi= _optmicrocode=() _optcmdline= _optsplash= _optkernelimage= _optuefistub=
+-_optshowautomods=0 _optsavetree=0 _optshowmods=0
++_optshowautomods=0 _optsavetree=0 _optshowmods=0 _optremove=0
+ _optquiet=1 _optcolor=1
+ _optskiphooks=() _optaddhooks=() _hooks=()  _optpreset=()
+ declare -A _runhooks _addedmodules _modpaths _autodetect_cache
+@@ -55,6 +55,8 @@ usage: ${0##*/} [options]
+    -n, --nocolor                Disable colorized output messages
+    -p, --preset <file>          Build specified preset from /etc/mkinitcpio.d
+    -P, --allpresets             Process all preset files in /etc/mkinitcpio.d
++   -R, --remove                 Remove specified preset images
++                                This option can only be used with either '-p|--presets' or '-P|--allpresets'
+    -r, --moduleroot <dir>       Root directory for modules (default: /)
+    -S, --skiphooks <hooks>      Skip specified hooks, comma-separated, during build
+    -s, --save                   Save build directory. (default: no)
+@@ -376,7 +378,7 @@ build_uefi(){
+ 
+ process_preset() (
+     local preset=$1 preset_cli_options=$2 preset_image= preset_options=
+-    local -a preset_mkopts preset_cmd
++    local -a preset_mkopts preset_cmd preset_remove_cmd
+     if (( MKINITCPIO_PROCESS_PRESET )); then
+         error "You appear to be calling a preset from a preset. This is a configuration error."
+         cleanup 1
+@@ -399,8 +401,13 @@ process_preset() (
+ 
+     ret=0
+     for p in "${PRESETS[@]}"; do
+-        msg "Building image from preset: $preset: '$p'"
++        if (( _optremove )); then
++             msg "Removing image for preset: $preset: '$p'"
++        else
++             msg "Building image from preset: $preset: '$p'"
++        fi
+         preset_cmd=("${preset_mkopts[@]}")
++        preset_remove_cmd=()
+ 
+         preset_kver=${p}_kver
+         if [[ ${!preset_kver:-$ALL_kver} ]]; then
+@@ -421,11 +428,13 @@ process_preset() (
+         preset_efi_image=${p}_efi_image
+         if [[ ${!preset_efi_image} ]]; then
+             preset_cmd+=(-U "${!preset_efi_image}")
++            preset_remove_cmd+=("${!preset_efi_image}")
+         fi
+ 
+         preset_image=${p}_image
+         if [[ ${!preset_image} ]]; then
+             preset_cmd+=(-g "${!preset_image}")
++            preset_remove_cmd+=("${!preset_image}")
+         elif [[ ! ${!preset_efi_image} ]]; then
+             warning "No image or efi_image file specified. Skipping image \`%s'" "$p"
+             continue
+@@ -443,9 +452,25 @@ process_preset() (
+             done
+         fi
+ 
+-        preset_cmd+=($OPTREST)
+-        msg2 "${preset_cmd[*]}"
+-        MKINITCPIO_PROCESS_PRESET=1 "$0" "${preset_cmd[@]}"
++        if (( _optremove )); then
++            if (( ${#preset_remove_cmd[*]} )); then
++                # we won't be calling mkinitcpio recursively, so no need to set MKINITCPIO_PROCESS_PRESET
++                for pr in "${preset_remove_cmd[@]}"; do
++                    if [[ ! -f "${pr}" ]]; then
++                        warning "Image not found: \`%s'" "$pr"
++                    elif [[ ! -w "${pr}" ]]; then
++                        error "Image not writable: \`%s'" "$pr"
++                    else
++                        rm -f -- "${pr}"
++                        msg2 "Removed: \`%s'" "$pr"
++                    fi
++                done
++            fi
++        else
++            preset_cmd+=($OPTREST)
++            msg2 "${preset_cmd[*]}"
++            MKINITCPIO_PROCESS_PRESET=1 "$0" "${preset_cmd[@]}"
++        fi
+         (( $? )) && ret=1
+     done
+ 
+@@ -482,10 +507,10 @@ preload_builtin_modules() {
+ trap 'cleanup 130' INT
+ trap 'cleanup 143' TERM
+ 
+-_opt_short='A:c:D:g:H:hk:nLMPp:r:S:sd:t:U:Vvz:'
++_opt_short='A:c:D:g:H:hk:nLMPp:Rr:S:sd:t:U:Vvz:'
+ _opt_long=('add:' 'addhooks:' 'config:' 'generate:' 'hookdir': 'hookhelp:' 'help'
+           'kernel:' 'listhooks' 'automods' 'moduleroot:' 'nocolor' 'allpresets'
+-          'preset:' 'skiphooks:' 'save' 'generatedir:' 'builddir:' 'version' 'verbose' 'compress:'
++          'preset:' 'remove' 'skiphooks:' 'save' 'generatedir:' 'builddir:' 'version' 'verbose' 'compress:'
+           'uefi:' 'microcode:' 'splash:' 'kernelimage:' 'uefistub:' 'cmdline:' 'osrelease:')
+ 
+ parseopts "$_opt_short" "${_opt_long[@]}" -- "$@" || exit 1
+@@ -539,6 +564,9 @@ while :; do
+             shift
+             _optpreset+=("$1")
+             ;;
++        -R|--remove)
++            _optremove=1
++            ;;
+         -n|--nocolor)
+             _optcolor=0
+             ;;
+@@ -627,6 +655,12 @@ if [[ -t 1 ]] && (( _optcolor )); then
+     try_enable_color
+ fi
+ 
++# if we get presets and remove flag, skip to preset processing
++if (( _optremove && ${#_optpreset[*]} )); then
++    map process_preset "${_optpreset[@]}"
++    exit
++fi
++
+ if [[ -n $_d_flag_hooks && -n $_d_flag_install ]]; then
+     _d_hooks=${_d_flag_hooks%:}
+     _d_install=${_d_flag_install%:}
+@@ -658,6 +692,8 @@ if [[ $KERNELVERSION != 'none' ]]; then
      [[ -d $_d_kmoduledir ]] || die "'$_d_kmoduledir' is not a valid kernel module directory"
  fi
  
@@ -444,6 +585,31 @@ index 3494fab..8acf414 100644
 +# Enable to speedup boot process, disable to save RAM
 +# during early userspace. Switch (yes/no).
 +#MODULES_DECOMPRESS="yes"
+diff --git a/shell/bash-completion b/shell/bash-completion
+index ddcec51..2db92df 100644
+--- a/shell/bash-completion
++++ b/shell/bash-completion
+@@ -57,7 +57,7 @@ _files_from_dirs() {
+ _mkinitcpio() {
+     local action cur prev opts
+     opts=(-A --addhooks -c --config -D --hookdir -d --generatedir -g --generate -H --hookhelp -h --help -k --kernel
+-          -L --listhooks -M --automods -n --nocolor -P --allpresets -p --preset -r --moduleroot
++          -L --listhooks -M --automods -n --nocolor -P --allpresets -p --preset -R --remove -r --moduleroot
+           -S --skiphooks -s --save -t --builddir -V --version -v --verbose -z --compress
+           -U --cmdline --kernelimage --microcode --osrelease --splash --uefi --uefistub)
+ 
+diff --git a/shell/zsh-completion b/shell/zsh-completion
+index a62ed90..8bcef17 100644
+--- a/shell/zsh-completion
++++ b/shell/zsh-completion
+@@ -52,6 +52,7 @@ case $service in
+             '(-n --nocolor)'{-n,--nocolor}'[Disable colorized output messages]' \
+             '(-P --allpresets)'{-P,--allpresets}'[Process all presets in /etc/mkinitcpio.d]' \
+             '(-p --preset)'{-p,--preset}'[Build specified preset from /etc/mkinitcpio.d]:presets:_files -g "*(\:r)" -W /etc/mkinitcpio.d' \
++            '--remove[Remove specified preset images]' \
+             '(-r --moduleroot)'{-r,--moduleroot}'[Root directory for modules (default: /)]:directory:_files -/' \
+             '(-S --skiphooks)'{-S,--skiphooks}'[Skip specified hooks, comma-separated, during build]:hook(s):_sequence -s , _path_files -W hookdirs' \
+             '(-s --save)'{-s,--save}'[Save build directory (default: no)]' \
 -- 
 2.38.1.143.g1fc3c0ad40
 
